export { criarAlocacao } from './criar-alocacao';
export { buscarAlocacoes } from './buscar-alocacoes';
export { buscarAlocacao } from './buscar-alocacao';
export { atualizarAlocacao } from './atualizar-alocacao';
export { excluirAlocacao } from './excluir-alocacao';
export { buscarGradeHorarios } from './buscar-grade-horarios-geral';
export { buscarAlocacoesPeriodoManha } from './buscar-alocacoes-periodo-manha';
export { buscarAlocacoesTurmaPeriodo } from './buscar-alocacoes-turma-periodo';
export { excluirTodasAlocacoesTurma } from './excluir-todas-alocacoes-turma';
